# Generated by Django 4.2.25 on 2026-01-02 10:17

from django.db import migrations, models
import plane.db.models.media


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0110_media_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='asset',
            field=models.FileField(max_length=800, upload_to=plane.db.models.media.get_media_upload_path),
        ),
    ]
